"""The finished review of one contract -- what goes in the memo.

Two kinds of output, kept apart on purpose:

  checks   deterministic tests with a pass/fail answer. Does the schedule foot?
           Is there an effective date? These are the things a reviewer would
           tick off without thinking, and a machine should never get wrong.
  flags    the judgment list from models/judgment.py. No pass/fail, because
           there is no answer to pass or fail against.

A memo that mixed them would let a reader skim past "the fee schedule doesn't
add up" as if it were one more thing to think about later. It isn't; it means
the extraction or the contract is broken, and everything downstream is suspect.
"""

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, Field

from revrec_contract_reviewer.models.citation import Citation
from revrec_contract_reviewer.models.extraction import ContractExtraction
from revrec_contract_reviewer.models.judgment import JudgmentFlag


class CheckOutcome(StrEnum):
    PASSED = "passed"
    FAILED = "failed"
    NOT_APPLICABLE = "not_applicable"


class ReviewCheck(BaseModel):
    """A deterministic test with a definite answer."""

    name: str
    outcome: CheckOutcome
    detail: str = Field(description="Plain-language result, generated by the check itself, never by a model.")
    evidence: list[Citation] = []


class ContractReview(BaseModel):
    """Everything the pipeline concluded, and everything it declined to conclude."""

    extraction: ContractExtraction
    checks: list[ReviewCheck] = []
    flags: list[JudgmentFlag] = []

    @property
    def doc_id(self) -> str:
        return self.extraction.doc_id

    def failed_checks(self) -> list[ReviewCheck]:
        return [check for check in self.checks if check.outcome is CheckOutcome.FAILED]

    def flags_in_review_order(self) -> list[JudgmentFlag]:
        """Judgments ordered by the step of the model they belong to.

        Ties keep the order the assessment raised them in, which follows the
        document, so two step-2 questions appear in the order a reader would
        meet them in the contract.
        """
        return sorted(self.flags, key=lambda flag: flag.step)

    def needs_review(self) -> bool:
        return bool(self.flags) or bool(self.failed_checks())

    def summary_line(self) -> str:
        """One line for the CLI's per-contract output."""
        failed = len(self.failed_checks())
        parts = [f"{len(self.flags)} judgment{'s' if len(self.flags) != 1 else ''}"]
        if failed:
            parts.append(f"{failed} failed check{'s' if failed != 1 else ''}")
        if self.extraction.dropped_for_no_evidence:
            parts.append(f"{self.extraction.dropped_for_no_evidence} dropped for no evidence")
        return f"{self.doc_id}: " + ", ".join(parts)
